spring:
  application:
    name: LiveStats
#  data:
#    redis:
#      host: localhost
#      port: 6379


server:
  port: 8080
  servlet:
    context-path: /api/

ixc:
  baseUrl: ${BASE_URL}
  id-user: ${ID_USER}
  token: ${TOKEN}