spring:
  application:
    name: LiveStats
#  data:
#    redis:
#      host: localhost
#      port: 6379

ixc:
  baseUrl: ${BASE_URL}
  id-user: ${ID_USER}
  token: ${TOKEN}

app:
  logo-url: ${APP_LOGO_URL}
  header-gradient: ${APP_HEADER_GRADIENT}
  header-font-color: ${APP_HEADER_FONT_COLOR}
